# Generated by Django 3.0 on 2019-12-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='sender')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
            ],
            options={
                'verbose_name': 'Blessing',
                'verbose_name_plural': 'Blessing',
            },
        ),
    ]
